export const ActionTypes = {
    Dashboard: {
        'SET_MAX_SPEND_LIMIT': "SET_MAX_SPEND_LIMIT",
        'SET_ACTIVE_OPTION': "SET_ACTIVE_OPTION",
        'SET_LOADING': "SET_LOADING_DASHBOARD",
        'SET_SUSSES_RESPONSE': "DAS_SET_SUSSES_RESPONSE",
        'SET_FAILURE_RESPONSE': "DAS_SET_FAILURE_RESPONSE"
    }
}